#!/usr/bin/bash

source /opt/ros/humble/setup.bash

build (){
    echo "building"
    rm -r install/ build/
    colcon build 
}

if [[ "$1" == "build" ]]; then
    build
fi

source install/setup.bash

ros2 run gym_asv_ros2 agent_node --ros-args -p agent:=./src/gym_asv_ros2/deploy_agent/agent.zip
