#!/usr/bin/bash

source /opt/ros/humble/setup.bash

rm -r install/ build/

colcon build 

source install/setup.bash

ros2 run gym_asv_ros2 agent_node --ros-args -p agent:=./src/gym_asv_ros2/deploy_agent/agent.zip
